/**:
  ros__parameters:
    common:
      database_storage: "mcap"                     # sqlite3 or mcap
      maximum_record_time: 36000                   # seconds
      maximum_allowed_bag_storage_size: 500.0      # GB
      maximum_bag_file_size: 20.0                  # GB
      enable_only_auto_mode_recording: false       # if enabled, recording occurs only "AUTO" mode
      record_all_topic_in_a_bag: true              # creates single bag file with input and other topics
      number_of_maximum_bags: 1000                 # limit of stored bag file count
      path: "bags/"                                # Path to bag file for saving
      prefix: "logging_ros2bag_"
      minimum_acceptable_disk_space: 50            # GB
      disk_space_threshold_action: "shutdown"      # [remove, shutdown] remove files or shutdown node
    raw_input_topics:                              # for rosbag-replay (logging) simulation
      record_raw_input: true
      raw_input_topics:
        - /sensing/gnss/(.*)
        - /sensing/imu/(.*)
        - /sensing/lidar/left/velodyne_packets
        - /sensing/lidar/right/velodyne_packets
        - /sensing/lidar/top/velodyne_packets
        - /vehicle/(.*)
    other_topics:                                  # all other topics
      record_other: true
      other_topics:
        - /api/(.*)
        - /autoware/(.*)
        - /awapi/(.*)
        - /control/(.*)
        - /diagnostics(.*)
        - /external/(.*)
        - /initialpose(.*)
        - /eagleye/(.*)
        - /localization/kinematic_state
        - /localization/pose_estimator/exe_time_ms
        - /localization/pose_estimator/initial_pose_with_covariance
        - /localization/pose_estimator/iteration_num
        - /localization/pose_estimator/nearest_voxel_transformation_likelihood
        - /localization/pose_estimator/pose
        - /localization/pose_estimator/pose_with_covariance
        - /localization/pose_estimator/transform_probability
        - /localization/pose_twist_fusion_filter/estimated_yaw_bias
        - /localization/pose_twist_fusion_filter/kinematic_state
        - /localization/pose_twist_fusion_filter/pose
        - /localization/pose_twist_fusion_filter/pose_with_covariance_without_yawbias
        - /localization/pose_twist_fusion_filter/pose_without_yawbias
        - /localization/pose_twist_fusion_filter/twist
        - /localization/pose_twist_fusion_filter/twist_with_covariance
        - /localization/pose_with_covariance
        - /localization/twist_estimator/gyro_twist
        - /localization/twist_estimator/gyro_twist_raw
        - /localization/twist_estimator/twist_with_covariance
        - /localization/twist_estimator/twist_with_covariance_raw
        - /perception/object_recognition/detection/apollo/objects$
        - /perception/object_recognition/detection/apollo/validation/objects
        - /perception/object_recognition/detection/centerpoint/objects
        - /perception/object_recognition/detection/centerpoint/validation/objects
        - /perception/object_recognition/detection/pointpainting/objects
        - /perception/object_recognition/detection/pointpainting/validation/objects
        - /perception/object_recognition/detection/pointpainting_roi_cluster_fusion/objects
        - /perception/object_recognition/detection/clustering/objects
        - /perception/object_recognition/detection/clustering/objects_with_feature
        - /perception/object_recognition/detection/clustering/camera_lidar_fusion/objects
        - /perception/object_recognition/detection/clustering/camera_lidar_fusion/objects_with_feature
        - /perception/object_recognition/detection/detection_by_tracker/debug/(.*)
        - /perception/object_recognition/detection/detection_by_tracker/objects
        - /perception/object_recognition/detection/objects_before_filter
        - /perception/object_recognition/objects
        - /perception/object_recognition/detection/objects
        - /perception/object_recognition/detection/rois(.*)
        - /perception/object_recognition/prediction/maneuver
        - /perception/object_recognition/objects$
        - /perception/object_recognition/tracking/objects
        - /perception/(.*)/traffic_signals
        - /perception/(.*)/detection/rois
        - /perception/(.*)/detection/rough/rois
        - /perception/(.*)/detection/expect/rois
        - /perception/occupancy_grid_map/map
        - /perception/traffic_light_recognition/fusion/traffic_signals
        - /perception/traffic_light_recognition/internal/traffic_signals
        - /perception/traffic_light_recognition/traffic_signals
        - /planning/mission_planning/checkpoint
        - /planning/mission_planning/goal
        - /planning/mission_planning/route
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/bound
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/avoidance_debug_message_array
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/lane_change_debug_message_array
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/(.*)
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/info/(.*)
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/input/lateral_offset
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/debug/parking_area
        - /planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/(.*)
        - /planning/scenario_planning/lane_driving/behavior_planning/debug/traffic_signal
        - /planning/scenario_planning/lane_driving/behavior_planning/path_with_lane_id
        - /planning/scenario_planning/lane_driving/behavior_planning/path
        - /planning/scenario_planning/lane_driving/force_lane_change
        - /planning/scenario_planning/lane_driving/lane_change_approval
        - /planning/scenario_planning/lane_driving/lane_change_candidate_path
        - /planning/scenario_planning/lane_driving/motion_planning/path_smoother/path
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/trajectory
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/virtual_wall
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/virtual_wall
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/debug/cruise/virtual_wall
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/debug/slow_down/virtual_wall
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/debug/marker
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/debug/stop_planning_info
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/debug/cruise_planning_info
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/debug/slow_down_planning_info
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/adaptive_cruise_control/debug_values
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/debug/marker
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop/debug_values
        - /planning/scenario_planning/lane_driving/motion_planning/obstacle_velocity_limiter/trajectory
        - /planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/(.*)
        - /planning/scenario_planning/lane_driving/trajectory
        - /planning/scenario_planning/max_velocity
        - /planning/scenario_planning/max_velocity_candidates
        - /planning/scenario_planning/max_velocity_default
        - /planning/scenario_planning/modified_goal
        - /planning/scenario_planning/motion_velocity_smoother/distance_to_stopline
        - /planning/scenario_planning/parking/trajectory
        - /planning/scenario_planning/scenario_selector/trajectory
        - /planning/scenario_planning/status/(.*)
        - /planning/scenario_planning/external_velocity_limit_selector/debug
        - /planning/scenario_planning/clear_velocity_limit
        - /planning/scenario_planning/current_max_velocity
        - /planning/steering_factor/(.*)
        - /planning/scenario_planning/trajectory
        - /planning/path_candidate/(.*)
        - /rosout
        - /system/(.*)
        - /tf(.*)
        - (.*)/debug/processing_time_ms
        - (.*)/debug/cyclic_time_ms
        - (.*)/virtual_wall/(.*)
        - /webauto(.*)